const Books = [
  {
    id: 1,
    title: "It Ends With Us",
    author: "Colleen Hoover",
    price: 798,
    image: "/books/colllin.webp",
    category: "Best Seller",
    rating: 4.7,
    genres: ["Romance", "Drama", "Contemporary"],
    description:
      "A heartbreaking yet hopeful novel about love, strength, and difficult choices. Lily has worked hard to build the life she wants, but when she meets Ryle, everything changes. However, when her first love reappears, her world is turned upside down.",
    pageCount: 384,
    isbn: 786657582,
    languages: "English",
    weight: 0.5,
  },
  {
    id: 2,
    title: "The Personal MBA",
    author: "Josh Kaufman",
    price: 1278,
    image: "/books/dale.webp",
    category: "Best Seller",
    rating: 4.5,
    genres: ["Business", "Self-Improvement", "Finance"],
    description:
      "A world-class business education in a single volume. Josh Kaufman breaks down key business concepts, from marketing to negotiation, in an easy-to-understand format for entrepreneurs and professionals alike.",
    pageCount: 464,
    isbn: 786657583,
    languages: "English",
    weight: 0.8,
  },
  {
    id: 3,
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    price: 320,
    image: "/books/deep.webp",
    category: "Best Seller",
    rating: 4.8,
    genres: ["Self-Help", "Psychology", "Communication"],
    description:
      "This timeless classic provides proven principles to improve social interactions, build relationships, and persuade others effectively. A must-read for anyone looking to improve their interpersonal skills.",
    pageCount: 288,
    isbn: 786657584,
    languages: "English",
    weight: 0.4,
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    price: 638,
    image: "/books/hill.webp",
    category: "Best Seller",
    rating: 4.6,
    genres: ["Productivity", "Business", "Self-Help"],
    description:
      "In an age of distractions, Deep Work highlights the importance of focused concentration. Cal Newport provides strategies to cultivate deep focus, increase productivity, and achieve meaningful results in your professional and personal life.",
    pageCount: 304,
    isbn: 786657585,
    languages: "English",
    weight: 0.7,
  },
  {
    id: 5,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 350,
    image: "/books/josh.webp",
    category: "Best Seller",
    rating: 4.9,
    genres: ["Finance", "Self-Improvement", "Success"],
    description:
      "Based on Hill’s extensive research of successful individuals, this book provides principles and strategies for achieving wealth, success, and financial freedom.",
    pageCount: 238,
    isbn: 786657586,
    languages: "English",
    weight: 0.3,
  },
  {
    id: 6,
    title: "Atomic Habits",
    author: "James Clear",
    price: 699,
    image: "/books/atomic.webp",
    category: "New Arrival",
    rating: 4.9,
    genres: ["Self-Help", "Productivity", "Psychology"],
    description:
      "A revolutionary book on habit formation, offering practical strategies to break bad habits and build good ones. Small changes lead to remarkable results.",
    pageCount: 320,
    isbn: 786657587,
    languages: "English",
    weight: 0.6,
  },
  {
    id: 7,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 540,
    image: "/books/subtle.webp",
    category: "New Arrival",
    rating: 4.4,
    genres: ["Self-Help", "Motivation", "Psychology"],
    description:
      "Mark Manson argues against conventional self-help wisdom, emphasizing the importance of embracing life's struggles, prioritizing what truly matters, and learning to let go of unimportant distractions.",
    pageCount: 224,
    isbn: 786657588,
    languages: "English",
    weight: 0.4,
  },
  {
    id: 8,
    title: "Olivia and Snowflake",
    author: "Julie Sykes",
    price: 540,
    image: "/books/olive.webp",
    category: "New Arrival",
    rating: 4.3,
    genres: ["Children", "Fantasy", "Adventure"],
    description:
      "An enchanting children's book following Olivia and her magical adventure with Snowflake, a talking kitten. A story full of friendship, wonder, and mystery.",
    pageCount: 32,
    isbn: 786657589,
    languages: "English",
    weight: 0.2,
  },
  {
    id: 9,
    title: "Count Zero",
    author: "William Gibson",
    price: 540,
    image: "/books/zero.webp",
    category: "New Arrival",
    rating: 4.2,
    genres: ["Science Fiction", "Cyberpunk", "Thriller"],
    description:
      "A cyberpunk classic set in a dystopian future filled with hackers, artificial intelligence, and high-stakes espionage. A must-read for sci-fi lovers.",
    pageCount: 320,
    isbn: 786657590,
    languages: "English",
    weight: 0.7,
  },
  {
    id: 10,
    title: "Educated",
    author: "Tara Westover",
    price: 799,
    image: "/books/educated.jpg",
    category: "New Arrival",
    rating: 4.8,
    genres: ["Biography", "Memoir", "Inspirational"],
    description:
      "A powerful memoir about a woman who escapes her survivalist upbringing to seek education and knowledge, overcoming immense obstacles to transform her life.",
    pageCount: 352,
    isbn: 786657591,
    languages: "English",
    weight: 0.6,
  },
  {
    id: 11,
    title: "Becoming",
    author: "Michelle Obama",
    price: 1200,
    image: "/books/becoming.webp",
    category: "Top Rated",
    rating: 4.9,
    genres: ["Memoir", "Biography", "Inspirational"],
    description:
      "Former First Lady Michelle Obama shares her life story, from her childhood in Chicago to her years in the White House, offering insights into resilience, leadership, and hope.",
    pageCount: 448,
    isbn: 786657592,
    languages: "English",
    weight: 0.9,
  },
  {
    id: 12,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 950,
    image: "/books/sapiens.webp",
    category: "Top Rated",
    rating: 4.8,
    genres: ["History", "Science", "Anthropology"],
    description:
      "A groundbreaking book that explores the history of humankind from the Stone Age to the present, explaining how humans evolved socially, politically, and culturally.",
    pageCount: 464,
    isbn: 786657593,
    languages: "English",
    weight: 1,
  },
  {
    id: 13,
    title: "The 5 AM Club",
    author: "Robin Sharma",
    price: 880,
    image: "/books/5amclub.webp",
    category: "Top Rated",
    rating: 4.5,
    genres: ["Self-Help", "Motivation", "Productivity"],
    description:
      "Robin Sharma shares the life-changing habits of early risers, demonstrating how waking up at 5 AM can improve productivity, mindset, and overall well-being.",
    pageCount: 336,
    isbn: 786657594,
    languages: "English",
    weight: 0.7,
  },
  {
    id: 14,
    title: "The Four-Hour Workweek",
    author: "Tim Ferriss",
    price: 1100,
    image: "/books/fourhour.webp",
    category: "Other",
    rating: 4.6,
    genres: ["Business", "Self-Help", "Entrepreneurship"],
    description:
      "Tim Ferriss shares unconventional strategies for achieving financial freedom, escaping the 9-to-5 grind, and designing a lifestyle that allows for travel and passive income.",
    pageCount: 416,
    isbn: 786657595,
    languages: "English",
    weight: 0.8,
  },
  {
    id: 15,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 550,
    image: "/books/alchemist.webp",
    category: "Other",
    rating: 4.7,
    genres: ["Fiction", "Philosophy", "Adventure"],
    description:
      "A mystical story about Santiago, a shepherd who embarks on a journey to find his personal legend. A deeply inspiring book about following one's dreams.",
    pageCount: 208,
    isbn: 786657596,
    languages: "English",
    weight: 0.4,
  },
  {
    id: 16,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    price: 600,
    image: "/books/now.webp",
    category: "Other",
    rating: 4.8,
    genres: ["Spirituality", "Self-Help", "Mindfulness"],
    description:
      "A life-changing book that teaches the importance of living in the present moment. Eckhart Tolle explores mindfulness and consciousness for a more fulfilling life.",
    pageCount: 236,
    isbn: 786657597,
    languages: "English",
    weight: 0.5,
  },
];

export default Books;
